#!/usr/bin/env python3
"""Deploy + stamp the canonical Claunker classifier into the chassis (vendoring).

claunker-hermes is the SOURCE OF RECORD for hermes_cli/claunker_classifier.py and
its test. This script vendors them into the chassis (hermes-agent) tree, stamping
the module with a provenance header so the runtime can prove the deployed file
matches canonical.

HASH DEFINITION (load-bearing — keep identical to the runtime self-check):
  The PROVENANCE_HASH is SHA-256 over the CANONICAL MODULE BODY, i.e. the raw
  bytes of claunker-hermes/hermes_cli/claunker_classifier.py exactly as committed.
  Canonical has NO provenance header; the header is chassis-only and is prepended
  here at deploy time. The deployed file is therefore:

      [provenance header] + [BODY_DELIMITER line] + [verbatim canonical body bytes]

  The delimiter is a fixed, unique sentinel so a runtime check (or this script's
  own self-verify) can split the header off and recompute SHA-256 over exactly the
  body bytes that follow it.

THREAT MODEL / WHAT THIS HASH DOES AND DOES NOT BUY (read before trusting it):
  * Body-only hashing catches ACCIDENTAL drift: a hand-edit to the deployed file's
    body changes the body bytes, so the recomputed hash no longer matches the
    PROVENANCE_HASH stamped in its own header -> the runtime self-check trips.
  * It does NOT, by itself, stop a DELIBERATE re-stamp: an attacker who edits the
    body can also recompute the hash and rewrite the header line, and the file is
    again internally consistent. Self-consistency is not authenticity.
  * Tamper-resistance therefore depends on WHERE the expected hash lives. The
    expected hash must sit somewhere the attacker editing the classifier file
    cannot also edit in the same breath — e.g. embedded in the chassis-versioned
    hook (plugins.py) and/or enforced in CI against the canonical repo, so a
    re-stamp shows up as a tracked diff. That runtime self-check + hash-location
    design is Pass 2; this script only establishes the canonical hash and the
    deploy/round-trip plumbing it will rely on.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

# ── Provenance header (module only) ─────────────────────────────────────────
# Three fixed lines; the third carries the body hash. The delimiter line that
# follows is the contract between deploy + runtime: everything strictly AFTER it
# (after its trailing newline) is the hashed body.
HEADER_TEMPLATE = (
    "# TACTICAL SECURITY CONTROL: VENDORED FROM CLAUNKER-HERMES\n"
    "# DO NOT EDIT THIS FILE DIRECTLY. CHANGES WILL BE OVERWRITTEN.\n"
    "# PROVENANCE_HASH: {hash}\n"
)
# Fixed, unique sentinel. MUST stay byte-stable across deploy + runtime self-check.
BODY_DELIMITER = (
    "# ===== BEGIN VENDORED BODY "
    "(sha256 in header covers every byte below this line) =====\n"
)

# ── Test banner (no hash — the test is vendored for convenience, not gated) ──
TEST_HEADER = (
    "# VENDORED FROM CLAUNKER-HERMES -- DO NOT EDIT THIS FILE DIRECTLY.\n"
    "# Source of record: claunker-hermes/tests/hermes_cli/test_claunker_classifier.py\n"
    "# Regenerate via scripts/deploy_classifier.py; direct edits will be overwritten.\n"
)

REPO_ROOT = Path(__file__).resolve().parent.parent
CANON_MODULE = REPO_ROOT / "hermes_cli" / "claunker_classifier.py"
CANON_TEST = REPO_ROOT / "tests" / "hermes_cli" / "test_claunker_classifier.py"

# Chassis-relative deploy targets.
REL_MODULE = Path("hermes_cli") / "claunker_classifier.py"
REL_TEST = Path("tests") / "hermes_cli" / "test_claunker_classifier.py"


def body_hash(body: bytes) -> str:
    """SHA-256 (hex) over the canonical module body bytes."""
    return hashlib.sha256(body).hexdigest()


def build_module_header(hash_hex: str) -> bytes:
    """The full header block (provenance lines + delimiter) as bytes."""
    return (HEADER_TEMPLATE.format(hash=hash_hex) + BODY_DELIMITER).encode("utf-8")


def stamp_module(body: bytes, hash_hex: str) -> bytes:
    """Deployed module bytes = header + delimiter + verbatim body."""
    return build_module_header(hash_hex) + body


def strip_header_body(deployed: bytes) -> bytes:
    """Recover the hashed body: everything strictly after the delimiter line.

    Splits on the FIRST occurrence of the delimiter so a (hypothetical) recurrence
    in the body can never move the boundary. Raises if the delimiter is absent."""
    marker = BODY_DELIMITER.encode("utf-8")
    idx = deployed.find(marker)
    if idx < 0:
        raise ValueError("body delimiter not found in deployed file")
    return deployed[idx + len(marker):]


def parse_header_hash(deployed: bytes) -> str:
    """Read the PROVENANCE_HASH value out of a deployed file's header."""
    head = deployed[: deployed.find(BODY_DELIMITER.encode("utf-8"))]
    for line in head.decode("utf-8", "replace").splitlines():
        if line.startswith("# PROVENANCE_HASH:"):
            return line.split(":", 1)[1].strip()
    raise ValueError("PROVENANCE_HASH line not found in deployed header")


def round_trip_ok(deployed: bytes, expected_hash: str) -> bool:
    """Strip the header, recompute SHA-256 over the body, compare to the header
    hash AND the independently-known expected hash. Fail-closed on any mismatch."""
    recovered = strip_header_body(deployed)
    stamped = parse_header_hash(deployed)
    recomputed = body_hash(recovered)
    return recomputed == stamped == expected_hash


def deploy(chassis: Path | None, dry_run: bool) -> int:
    if not CANON_MODULE.is_file():
        print(f"ERROR: canonical module missing: {CANON_MODULE}", file=sys.stderr)
        return 2
    if not CANON_TEST.is_file():
        print(f"ERROR: canonical test missing: {CANON_TEST}", file=sys.stderr)
        return 2

    body = CANON_MODULE.read_bytes()
    test_body = CANON_TEST.read_bytes()
    h = body_hash(body)
    deployed = stamp_module(body, h)

    mod_target = (chassis / REL_MODULE) if chassis else None
    test_target = (chassis / REL_TEST) if chassis else None

    print("=" * 78)
    print("Claunker classifier deploy" + ("  [DRY RUN -- writes NOTHING]" if dry_run else ""))
    print("=" * 78)
    print(f"canonical module : {CANON_MODULE}")
    print(f"canonical test   : {CANON_TEST}")
    print(f"module target    : {mod_target or '<chassis>/' + REL_MODULE.as_posix()}")
    print(f"test target      : {test_target or '<chassis>/' + REL_TEST.as_posix()}")
    print()
    print(f"PROVENANCE_HASH (sha256 over canonical body) = {h}")
    print()
    print("Header that would be stamped onto the deployed module:")
    print("-" * 78)
    sys.stdout.write(build_module_header(h).decode("utf-8"))
    print("-" * 78)

    # Round-trip the in-memory stamped bytes: strip header -> recompute -> compare.
    if not round_trip_ok(deployed, h):
        print("FAIL: body-hash round-trip mismatch on freshly-stamped bytes.",
              file=sys.stderr)
        return 1
    print("body-hash round-trip: OK "
          "(stripped header, recomputed sha256 over body == header hash == canonical hash)")
    print()

    if dry_run:
        print("DRY RUN: no files written to the chassis. Re-run without --dry-run "
              "(Pass 2) to stamp and deploy for real.")
        return 0

    # ── Real write path (Pass 2 uses this) ──────────────────────────────────
    if chassis is None:
        print("ERROR: --chassis is required for a real deploy (set --chassis or "
              "$HERMES_AGENT_DIR).", file=sys.stderr)
        return 2

    mod_target.parent.mkdir(parents=True, exist_ok=True)
    test_target.parent.mkdir(parents=True, exist_ok=True)
    mod_target.write_bytes(deployed)
    test_target.write_bytes(TEST_HEADER.encode("utf-8") + test_body)
    print(f"wrote module: {mod_target}")
    print(f"wrote test  : {test_target}")

    # Self-verify: re-read from disk, strip header, recompute, assert. Fail-closed.
    on_disk = mod_target.read_bytes()
    if not round_trip_ok(on_disk, h):
        print("FAIL: deployed module failed self-verify (body hash != header hash). "
              "Deploy is NOT trustworthy.", file=sys.stderr)
        return 1
    print("self-verify: OK (re-read deployed module, body hash matches stamped header)")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--chassis",
        default=os.environ.get("HERMES_AGENT_DIR"),
        help="Path to the chassis (hermes-agent) source tree. Defaults to "
             "$HERMES_AGENT_DIR. Required for a real (non-dry-run) deploy.",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute the hash, print the header that would be stamped, confirm the "
             "body-hash round-trips, and write NOTHING. (Pass 1 default usage.)",
    )
    args = ap.parse_args(argv)
    chassis = Path(args.chassis).resolve() if args.chassis else None
    return deploy(chassis, args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
